import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";
import ReownProvider from "./provider/reown-provider";
import { headers } from "next/headers";
import "./globals.css";
import ChakraProviderWrapper from "./provider/chakra-provider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersObj = await headers();
  const cookies = headersObj.get('cookie')

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} ${geistMono.variable}`}>
        <ChakraProviderWrapper>
          <ReownProvider cookies={cookies}>
            {children}
          </ReownProvider>
        </ChakraProviderWrapper>
      </body>
    </html>
  );
}
